### ISSUE TITLE
Mysql timeout configurations not being respected

### ISSUE THREAD

**Issue by BayoKwendo** [denodrivers/mysql#86] opened 2020-10-15 09:01 UTC
I have been monitoring my deno mysql application for sometime now. Even though i included everything suggested for this driver , idletimout etc but my application keeps on disconnecting after idle for 10 minutes or more.,, i am just stuck and wondering why deno cant respect MySQL configurations. 
And wait why cant you implement keep-alive function

**Comment by lideming** [comment] 2020-10-15 09:21
More information is needed.
What are the value of MySQL server wait_timeout and the idleTimeout option?
Does deno_mysql connect to a remote MySQL server or a localhost one? If connecting remotely, the TCP connection can be broken due to unstable network or router NAT timeout etc. If it is the case, try setting idleTimeout to a lower value, 60000 (1 minute) for example.

**Comment by BayoKwendo** [comment] 2020-10-15 09:30
I have set MySQL server timeout configurations to be 24 hours and idletimeot to be 3 hours. MySQL is hosted remotely. and still been experiencing this.

**Comment by lideming** [comment] 2020-10-15 09:45
So I think there is some network problem between the client and the server.

You can set `idleTimeout` to `300000` (5 minutes) and see if the problem still persists.

I will consider implementing heartbeat packets in deno_mysql.

**Comment by BayoKwendo** [comment] 2020-10-15 09:59
Great, lemme try,, heartbeat packet would be the best solution

**Comment by BayoKwendo** [comment] 2020-10-16 13:05
Any hope for us..  the heartbeat thing?

**Comment by lideming** [comment] 2020-10-16 13:16
Seems that there is no heartbeat in the protocol of MySQL.
Maybe using `idleTimeout` is the correct way.

**Comment by BayoKwendo** [comment] 2020-10-18 01:34
ok but unfortunately idleTimout is not being respected also. I have test and test with all same result after a 10 minutes "connection closed"

**Comment by lideming** [comment] 2020-10-18 03:27
@BayoKwendo 
Is there "connection idle timeout" before "connection closed"?

**Comment by BayoKwendo** [comment] 2020-10-18 09:15
It varies, sometimes it say closed unexpectedly, sometime connection idle timeout

**Comment by lideming** [comment] 2022-11-25 15:29
Can't reproduce the problem. Close it for now.

**Closed by lideming** 2022-11-25 15:29 UTC
